### ISSUE TITLE
Arrow missing?

### ISSUE THREAD

**Issue by hvgeertruy** [carrot/share-button#124]
Like you show in the demo:

![demo](https://camo.githubusercontent.com/863a68c6e85869408219e296800ba78dadc7e9ce/68747470733a2f2f692e636c6f756475702e636f6d2f5254494f5a6578392d692e676966)

There's a arrow shown below the facebook icon.
But it's not in the final implementation.

I rather liked that arrow, tbh. Why did it have to go? Is it intentional?

**Comment by jenius** [comment]
Yeah I agree. The arrow was a casualty of making more networks available to add/remove from the popup. The logic to detect networks have been added/removed then position and color the arrow correctly seemed ridiculous. I liked it too though and would like to get it added back in at some point.

**Comment by tmilewski** [comment]
I too like the arrow but making it work in all scenarios, short of being quite a bit of ongoing effort, isn't possible given the current state of the design and functionality. For example, in the situation when there's an even number of networks.

I'm going to close this for now. If there comes a time where it makes sense design-wise, etc to add the arrow back in, we'll certainly do so.

Thanks!
