### ISSUE TITLE
Wishlist: Add Whatsapp button

### ISSUE THREAD

**Issue by martinbetz** [carrot/share-button#130]
Whatsapp now supports sharing by URL and there is already [one implementation](http://whatsapp-sharing.com/) out there.

I think this is a great candidate for a nex integration.

The only problem is see is that you should hide it when being viewed on a non-mobile device. When using a CSS framework such as [UIKit](http://www.getuikit.com) I would wrap it in a `div` that does not show up at certain media-queries.

**Comment by tmilewski** [comment]
Thanks! This has been noted and I'm closing in it favor of #160 and a v1.0 release.
