### ISSUE TITLE
Facebook errors

### ISSUE THREAD

**Issue by tgcreate** [carrot/share-button#135]
Am absolutely loving this, but I'm finding that whenever I attempt a Facebook share, the popup gives me this error message: "An error occurred. Please try later."

When I click OK, the popup does take me to Facebook, but the preloaded share is gone.

I'm probably doing something wrong, but I'm not sure. I didn't change the app_id. Am I supposed to replace that with one I get from Facebook myself?

**Comment by zreitano** [comment]
My app_id is coming out blank in the url. Here is my config 

```var config = {
                    url: "http://urx.io/useshout.com/app/shouts/" + post_attributes.id,
                    title: "Check out this Shout: " + post_attributes.title,
                    description: post_attributes.description,
                    image: image,
                    networks: {
                        facebook: {
                            app_id: "app_id_in_here",
                        },
                        google_plus: {
                            enabled: true
                        },
                        twitter: {
                            enabled: true
                        },
                        pinterest: {
                            enabled: true
                        },
                        email: {
                            enabled: true
                        }
                    }
                }
```

Any help would be awesome!

**Comment by zreitano** [comment]
In debugger mode in the Chrome console, my config object looks like this:

config
Object {url: "http://urx.io/useshout.com/app/shouts/8180", title: "Check out this Shout: Yup", description: "They are pretty sweet!!!!", image: "http://shoutdevelopment.s3.amazonaws.com/posts/818…6500&Signature=MjfI%2BTtGDJti%2FjasxJsB6COFQtY%3D", networks: Object}

config.networks
Object {facebook: Object, google_plus: Object, twitter: Object, pinterest: Object, email: Object}

config.networks.facebook
Object {app_id: "my_app_id"}
