### ISSUE TITLE
Instagram?

### ISSUE THREAD

**Issue by marvoh** [carrot/share-button#147]
Great plugin, more social networks the better :-)

**Comment by kylemac** [comment]
@marvoh I don't believe there is anyway to share a piece of content from a website to instagram. do you know of any technique?

**Comment by kylemac** [comment]
i'm going to close this for now. if you _do_ have a technique or one comes along, feel free to reopen @marvoh

**Comment by marvoh** [comment]
Hey, sorry for late response, you're right there's no way to do so.
