### ISSUE TITLE
Twitter Cards

### ISSUE THREAD

**Issue by marvoh** [carrot/share-button#148]
I am having trouble getting cards to work with this. I'm I getting something wrong because I have set up well including meta information and cards approved by twitter

        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@monarstrategic">
        <meta name="twitter:title" content="Bless a needy child this Easter. #SelltoBless">
        <meta name="twitter:description" content="I am selling my <?php echo $_GET['item']; ?> on OLX to buy foodstuff and drop at any Tuskys to bless a needy child this Easter. Join me http://bit.ly/OLXKESellToBless &#35;SelltoBless">
        <meta name="twitter:image" content="<?php echo $_GET['image'] ?>">
        <meta name="twitter:url" content="http://selltobless.org">

**Comment by tmilewski** [comment]
Thanks! Closing in favor of #161 and a v1.0 release.

**Comment by hhsnopek** [comment]
@marvoh how were you testing this?
