### ISSUE TITLE
Newlines in description text disappear when sharing email

### ISSUE THREAD

**Issue by vigna** [carrot/share-button#154]
All CR/LF characters disappear when a piece of text is shared using the email button.

**Comment by jenius** [comment]
Yeah, I think this is actually a limitation of mailto links. I did a bunch of research into this a while back, and while it's possible to get newlines to render in a couple of random email clients if they are escaped, most of them will not render a newline from a mailto link.

This is rather unfortunate, but I would recommend simply using a one liner or a single paragraph for the email share because of this :confused:

**Comment by vigna** [comment]
No, that's just the entirely crazy encode() function that was "checking" for a string being "already encoded" with a quite unlikely heuristic that was passed by our email text. Don't know why. We just eliminated the check:

 ShareUtils.prototype.encode = function(str) {
    if (typeof str === "undefined") {
      return str;
    } else {
      return str.to_rfc3986();
    }
  };

Everything works fine now.

**Comment by jenius** [comment]
If I'm not mistaken, theres a good reason why we encode the data first. @tmilewski would probably be able to tell you more about this.

It might work fine in whatever email client you are opening it in at the moment, but I definitely recall testing newlines in a bunch of different email clients and having it not work in many of them. If you have tested across a wide range and it works in all of them, a lot of progress must have been made and that's great.

Either way, I'll have to look into encoding and mailto links to see if it's safe enough across clients to create an exception for this property.

**Comment by vigna** [comment]
The point is not about newlines—the point is that "testing for being encoded" in is_encoded() is entirely crazy. You must know which of your data is encoded or not. Encoding and decoding and testing for differences should give you always false, or your coding functions are broken.

**Comment by jebsky** [comment]
@vigna From what you posted I am not entirely sure how to get newlines to work in the email

**Comment by vigna** [comment]
> On 29 Jul 2015, at 20:17, Jeffrey Balinsky <notifications@github.com> wrote:
> 
> @vigna From what you posted I am not entirely sure how to get newlines to work in the email

I think the basic point was to remove the "is_encoded" from


                ShareUtils.prototype.encode = function(str) {
                        if (typeof str === "undefined") {
                                return str;
                        } else {
                                return str.to_rfc3986();
                        }
                };

but the problem is that now the source is in coffee, so I have no way to do an easy diff.

Ciao,

					seba
