### ISSUE TITLE
Unable to override CSS styles

### ISSUE THREAD

**Issue by bfeist** [carrot/share-button#155]
The CSS docs aren't explicit on implementation. Including any of the provided CSS classes in an external css file causes those instances to be overridden by the CSS injected by share.js.

Please provide detail on how to use the CSS classes to style the interface.

**Comment by bfeist** [comment]
here's a fiddle to illustrate https://jsfiddle.net/bfeist/50ssn0rh/3/

**Comment by detarmstrong** [comment]
The css selector must be made more specific in order to override the pre-defined css. I've updated the fiddle here: https://jsfiddle.net/50ssn0rh/8/. Note "div" precedes the selector, making it more specific. Also, enabled: "false" should be enabled: false.

**Comment by bfeist** [comment]
Thanks so much!
