### ISSUE TITLE
Video sharing

### ISSUE THREAD

**Issue by leemarcus27** [carrot/share-button#157]
Hi, I  have been trying to figure out how to add video sharing in twitter and facebook. I started out trying to add an video element in the javascript to get the video using the video file path but when I test the share button the popup facebook dialog doesn't add the video. Any help on this?

**Comment by tmilewski** [comment]
@leemarcus27 Sharing videos is something that is quite a bit beyond both the capabilities and intentions of this library. 

Here's more information on uploading videos to Facebook that might help you out: https://developers.facebook.com/docs/graph-api/reference/video
