### ISSUE TITLE
Email contains no URL

### ISSUE THREAD

**Issue by webfeuerflo** [carrot/share-button#158]
When clicking the mail-button the E-Mail opens and the body contains the title of the Webpage the button is on but there is no clickable URL, so it doesn't make any sense.
How can I get the URL in the Mail?

Tested on Apple Mail.

**Comment by webfeuerflo** [comment]
ok, found this closed issue: https://github.com/carrot/share-button/issues/105
it works and displays the url, but it is no link. 
any idea how to make it clickable?

**Comment by tmilewski** [comment]
That very much depends on the the email client. We're quite limited beyond that. Sorry.
