### ISSUE TITLE
Support for Twitter Card meta tags

### ISSUE THREAD

**Issue by tmilewski** [carrot/share-button#161]
View updated valid Twitter Card meta tags [here](https://dev.twitter.com/cards/markup).

Ref: #148

**Comment by hhsnopek** [comment]
After investigating twitter cards, to use these you must be allow the TwitterBot to access your site, more specifically your link. see https://dev.twitter.com/cards/getting-started#crawling

Basically the TwitterBot will scan the site for the tags and grab the twitter card info via the meta tags (`og` or `twitter`). So long as you're testing this on a site that is live and you are allowing the TwitterBot to scan via your Robots.txt, this will work (with no conflict from share-button)

**Comment by hhsnopek** [comment]
You just need to have the og tags or the twitter meta tags while allowing the twitter bot to crawl your site and you'll be able to use twitter meta cards.
