### ISSUE TITLE
Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by t0t** [carrot/share-button#180]
Hello,
I got this. Any suggestion?
thanks.
![captura de pantalla 2015-06-20 a las 11 26 03](https://cloud.githubusercontent.com/assets/6004806/8266701/3d3bcef0-173d-11e5-94f8-7078aa6ca5d6.png)

**Comment by hhsnopek** [comment]
I replicated as best I could locally with your and I'm surprised you didn't get this:
```
Invalid App Id: Must be a number or numeric string representing the application id.               all.js:64 
FB.getLoginStatus() called before calling FB.init().                                                                  all.js:64 
```

**Comment by hhsnopek** [comment]
When are you requiring this script? If it's before the `body` loads, this could be the problem. I recommend moving the any js script to the end of the `body` element
