### ISSUE TITLE
Network Hooks

### ISSUE THREAD

**Issue by leemarcus27** [carrot/share-button#191]
I'm trying to set network hooks with the share button. Facebook is the only one that works when loading the data  elements. 

new Share(".share-button", {
        ui: {
        flyout: "top center",
        button_text: "Share"
      },
  networks: {
    facebook: {
        app_id: "1582499538701972",
      before: function(element) {
        this.title = element.getAttribute("data-title");
        this.url = element.getAttribute("data-url");
        this.image = element.getAttribute("data-image");
        this.description = element.getAttribute("data-description");         
      },
      after: function() {
        console.log("User shared:", this.url);
        console.log("User shared:", this.title);
        console.log("User shared:", this.image);
      }
    },
    twitter: {
        before: function(element) {
        this.title = element.getAttribute("data-title");
        this.url = element.getAttribute("data-url");
        this.image = element.getAttribute("data-image");
        this.description = element.getAttribute("data-description");         
      },
      after: function() {
        console.log("User shared:", this.url);
        console.log("User shared:", this.title);
        console.log("User shared:", this.image);
      }
        
    },
    pintrest:{
       before: function(element) {
        this.title = element.getAttribute("data-title");
        this.url = element.getAttribute("data-url");
        this.media = element.getAttribute("data-image");
        this.description = element.getAttribute("data-description");         
      },
      after: function() {
        console.log("User shared:", this.url);
        console.log("User shared:", this.title);
        console.log("User shared:", this.image);
      } 
    }
  }
});

with pintrest nothing is shared except for the actual website url. And twitter only shares the description the url doesn't apply. Am I calling the network hooks wrong?

**Comment by hhsnopek** [comment]
Checkout the latest version :) this should be fixed
