### ISSUE TITLE
facebook share returns error

### ISSUE THREAD

**Issue by ragsnas** [carrot/share-button#192]
I tried to implement your share Button yet it seems it does not work with the SDK for some reason.
[Here's the plunkr](http://plnkr.co/edit/mm8qfWlZ04ZpWLApAhCd?p=preview).

So it calls this url:
https://www.facebook.com/dialog/feed?app_id=1574474959507293&caption=caption&description=description&display=popup&e2e=%7B%7D&link=http%3A%2F%2Frun.plnkr.co%2FiY96egGzcwP4eHed%2F&locale=en_US&name=testtitle&next=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FxRlIuTsSMoE.js%3Fversion%3D41%23cb%3Dfd27373fc%26domain%3Drun.plnkr.co%26origin%3Dhttp%253A%252F%252Frun.plnkr.co%252Ffa312675%26relation%3Dopener%26frame%3Df69e1dcd4%26result%3D%2522xxRESULTTOKENxx%2522&picture=https%3A%2F%2Fmedia4.giphy.com%2Fmedia%2F2Oill0NhlWZmo%2F200_s.gif&sdk=true

Returning an unspecific Error Page ("Error occured. Please try again later).

The app_id is valid and i do not see the problem realy :-/

**Comment by HJThompson** [comment]
+1

**Comment by Kasendwa** [comment]
That is actually happening to me too. However, i've realized that happens only to accounts that haven't authorized the application.

**Comment by assortex** [comment]
+ 1

Also, I would like to have this upgraded to the new version of the sharer. More info: http://okaypl.us/blog/facebook-share-dialog-longer-accepts-custom-parameters/

**Comment by hhsnopek** [comment]
@ragsnas & @HJThompson have you tried authorizing your app then using the SDK again?

**Comment by hhsnopek** [comment]
Hey, due to the inactivity I'm going to close this - let me know if this still persists and reopen the thread :smile:
