### ISSUE TITLE
Rearrange order of icons

### ISSUE THREAD

**Issue by Viriathus** [carrot/share-button#193]
Is there an option to rearrange the order of the social buttons. For example I'd like to have fb to come 1st then twiiter, gplus, pinterest.
Thanks!

**Comment by hhsnopek** [comment]
Currently there isn't, but I think this is a good feature - we'll get this in v1.0.x

**Comment by Viriathus** [comment]
Cool thank you!

**Comment by hhsnopek** [comment]
available in current release :)
