### ISSUE TITLE
Use as static row of buttons

### ISSUE THREAD

**Issue by brandones** [carrot/share-button#197]
I'd like to just show the row of share buttons, rather than having to click the "Share" button to reveal it. Having a config option to do this would be great.

**Comment by kylemac** [comment]
@brandones surprisingly enough, this is actually against our original intention of the `share-button`. we were tired of the spattered share buttons one all of these sites and wanted to see if we could make a little cleaner and more concise solution to the sharing problem. 

that said, we don't deny that there are use-cases out there to display the buttons on their own. while we may not prioritize this feature with a config option right now, you may realize you can probably still accomplish this effect. by using the `share.open()` function in the [public api](https://github.com/carrot/share-button#public-api) you could reveal the network buttons and then use CSS to remove the "share" button itself.

**Comment by brandones** [comment]
Hack for those interested:

JS:
```
var share = new Share("#share-button", {
  ui: {
     flyout: 'middle middle'
  }
});
    share.open();
```

CSS:
```
div.social {
    margin-left: -80px !important;
}
```

**Comment by kylemac** [comment]
much appreciated @brandones. I'm sure others will find this helpful
