### ISSUE TITLE
Email not working in Safari [ only iPhone ]

### ISSUE THREAD

**Issue by chiragchoudhary66** [carrot/share-button#199]
Sharing through email doesn't seem to be working in safari on the iPhones (tested on iphone 5 and 4). It simply opens a new tab and stops instead of opening the mail app. Works fine on the iPads as well.

**Comment by chiragchoudhary66** [comment]
Found the fix for the issue --> Change the name attribute in the window.open function to "_self".

so change this :+1: 

window.open(t+i,"targetwindow","toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,left="+n.left+",top="+n.top+",width="+n.width+",height="+n.height)

to this : 

window.open(t+i,"_self","toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,left="+n.left+",top="+n.top+",width="+n.width+",height="+n.height)

**Comment by hhsnopek** [comment]
confirmed bug, does your fix also work on desktop still and other browsers?

**Comment by hhsnopek** [comment]
see #260
