### ISSUE TITLE
Pinterest Invalid Image URI

### ISSUE THREAD

**Issue by paramsinghvc** [carrot/share-button#201]
When I hit the pinterest share button, it shows me a popup with invalid image URI on the demo page itself. Also, on my local implementation, its showing the same error.
![screen shot 2015-07-29 at 2 31 01 pm](https://cloud.githubusercontent.com/assets/4329912/8953849/17fb7628-35ff-11e5-8087-feec7aa5db51.png)

**Comment by kylemac** [comment]
@paramsinghvc can you share the URL that's being generated please?

**Comment by hhsnopek** [comment]
@paramsinghvc is this still an issue or was it resolved? the URL's are encoded properly. Please reopen this if it's still occurring.
