### ISSUE TITLE
Cleaner way to default all networks to false

### ISSUE THREAD

**Issue by AntonRand** [carrot/share-button#203]
I'd only like to have options to share with Google+, Facebook and Twitter.

I have to set enabled on all of the other networks to be false, but if a new network was added I'd have to update my configuration. 

![image](https://cloud.githubusercontent.com/assets/3882274/9193504/cf5ff15c-400b-11e5-8a0f-727df202e9a8.png)

Can we set enabled to be false by default through the configuration so we only take into account networks that have been defined in the configuration? Would help clear up the verbose config

**Comment by hhsnopek** [comment]
The only thing I have against this is those that use all the networks and/or disable one or two networks. Either way one is going to have a verbose object, I'm personally against this unless a majority of users are disabling a lot of the networks.
