### ISSUE TITLE
button_text configuration parameter ignored

### ISSUE THREAD

**Issue by AntonRand** [carrot/share-button#204]
My web page is multi-lingual and as a result I want to dynamically set the button text. I've used the 'button_text' parameter as described in the wiki configuration documentation but the text remains set to Share.

![image](https://cloud.githubusercontent.com/assets/3882274/9224440/3c604a88-40fa-11e5-9b2c-4da784a84052.png)

**Comment by AntonRand** [comment]
Just looked at the source code, the Wiki is not referring to the correct parameters:

Should be buttonText and not button_text

I've updated the Wiki.

**Comment by tmilewski** [comment]
Sorry and thanks @AntonRand!
