### ISSUE TITLE
bower version not updated

### ISSUE THREAD

**Issue by yosefs** [carrot/share-button#212]
bower version id 0.5 instead 1.*.* the current version

**Comment by hhsnopek** [comment]
with the latest release "tagged", you'll be installing 1.0.2 now :)

**Comment by jeveloper** [comment]
Reopen this or i can make another one, in 1.0.2 you removed dist from repo, hence using bower will not work.

**Comment by hhsnopek** [comment]
@jeveloper

**Comment by jeveloper** [comment]
@hhsnopek First of all, thank you for your good work !

I did make it work in my requirejs environment , but as you know bower libs needs to be shipped with both non min and min versions of a distribution, that way it works well. However i understand why you chose a different path, its a lib that has to be minimal.

**Comment by hhsnopek** [comment]
Thank you @jeveloper - I've figured out how this is going to be handled and hopefully will have it up later today, if not this weekend

**Comment by hhsnopek** [comment]
pending the ability to publish to bower thru authorship, bower will be updated hopefully by EOD.

**Comment by hhsnopek** [comment]
updated and working!
