### ISSUE TITLE
Wrong Pioneer Version

### ISSUE THREAD

**Issue by ncksllvn** [carrot/share-button#221]
I tried to install share-button via NPM and encountered this error:

`npm ERR! version not found: pioneer@1.11.5`

I believe this version was specified in the package.json by mistake because the highest version of Pioneer is 0.11.6.

**Comment by ncksllvn** [comment]
Added PR #222

**Comment by ncksllvn** [comment]
Also, shouldn't Pioneer be a devDependency instead of a standard dependency?

**Comment by ncksllvn** [comment]
I opened PR #223 to include the latest version of Pioneer and it installed fine through NPM.

**Comment by mahemoff** [comment]
+1
