### ISSUE TITLE
I have a question: How do you user FB.ui for open new window?

### ISSUE THREAD

**Issue by cawa-93** [carrot/share-button#225]
In your example you are using the FB.ui method and you have a new window opens with URL:
`https://www.facebook.com/dialog/feed?app_id=...`

![2015-09-21 11 14 04](https://cloud.githubusercontent.com/assets/1662812/9987599/e625dcd8-6051-11e5-9208-fa79009db1d3.png)

I tried to make the same realization on his website, but instead of a new window I get an interactive element #fb-root

![2015-09-21 11 12 05](https://cloud.githubusercontent.com/assets/1662812/9987576/bb8123de-6051-11e5-9f87-ecaeabdd955e.png)

What am I doing wrong?

**Comment by mahemoff** [comment]
I'm curious why you don't want the interactive element? I see the opposite - it starts to expand the interactive element and then it opens a new window instead.

I haven't investigated, but I'm guessing it may depend on how you've configured your app's settings in Facebook's dashboard. For security reasons, you might need to indicate the domain(s) where you'll embed this.

**Comment by hhsnopek** [comment]
@mahemoff is on the right track, I'm personally not familiar enough with the Facebook SDK/dashboard to provide more help but definitely start looking there. The sharebutton just uses the SDK if provided, take a look at the settings from facebook.
