### ISSUE TITLE
Demo page using old version of code?

### ISSUE THREAD

**Issue by CostaC** [carrot/share-button#230]
Any reason http://sharebutton.co/ uses an older version of the code? And it uses 

```
new Share(".share-button")
```
instead of  `new ShareButton`.

I ask because while I can get the email popup to appear is I use the js file from sharebutton.co, I can't get the popup to appear with the latest code.

**Comment by hhsnopek** [comment]
Yeah I'm actually working on that right now! I apologize for the confusion, it is `new ShareButton` - I'll have these changes up tonight hopefully

**Comment by CostaC** [comment]
FYI, found these that still use old function name:

https://github.com/carrot/share-button/wiki/Network-Hooks 
https://github.com/carrot/share-button/wiki/Network-Hooks
https://github.com/carrot/share-button/blob/master/examples.html

**Comment by hhsnopek** [comment]
The wiki will be disabled after the update tonight as I'll have a folder containing all the docs and references to the code

**Comment by Chrysweel** [comment]
:+1:

**Comment by hhsnopek** [comment]
no longer an issue! :)
