### ISSUE TITLE
Error when defining `new ShareButton(element)`

### ISSUE THREAD

**Issue by allybee** [carrot/share-button#232]
When attempting to attach ShareButton to a specific element, I get the error:
[ShareButton.js:862](https://github.com/carrot/share-button/blob/master/dist/ShareButton.js#L862) ```Uncaught TypeError: instances[Symbol.iterator] is not a function```

Without being able to define which element to attach to, you can't have multiple share buttons with separate configurations.

```html
<share-button class="share-button-01"></share-button>
<share-button class="share-button-02"></share-button>

<script>
    new ShareButton( '.share-button-01' , { /* some options */ } );
    new ShareButton( '.share-button-02' , { /* different options */ } );
</script>
```

**Comment by hhsnopek** [comment]
Hey @allybee what browser are you using?

**Comment by allybee** [comment]
Oops, should have included that! Chrome for Mac v45.0.2454.101 (64-bit)

**Comment by allybee** [comment]
@hhsnopek Thank you so much! I've tested it and it works great.

**Comment by hhsnopek** [comment]
@allybee no problem! I'll be cutting a release shortly as well
