### ISSUE TITLE
Example fails. No dist folder

### ISSUE THREAD

**Issue by macsupport** [carrot/share-button#234]
Missing dist folder? index.html references ````<link href="dist/share-button.min.css" rel="stylesheet">```` but dist is not in the repo.

**Comment by hhsnopek** [comment]
Yup, we've removed the `dist` folder from the repo - I'm getting a couple more things into master before I cut a release!

**Comment by macsupport** [comment]
OK. A bit confusing to download and not have the css file included in the zip.

**Comment by hhsnopek** [comment]
It is, but take a look at the releases and download the versioned release, this contains the 'dist' with everything compiled in it. We also have the last files separately under the latest release. We keep the compiled files out of the repo to keep everything a bit more tidy



--
Henry Snopek
