### ISSUE TITLE
Release 1.0.2 share-button.min.css file has local link to google font

### ISSUE THREAD

**Issue by dkleissa** [carrot/share-button#237]
in share-button.min.css the font url(../../Users/henrysnopek/projects/share-button/http:/fonts.gstatic.com/s/lato/v11/v0SdcGFAl2aezM9Vq_aFTQ.ttf) included which causes an error.

If you delete the local part and fix the url to https:// (in my case) it works.

**Comment by hhsnopek** [comment]
Yeah this is odd and I think I've come upon it in the past, in the stylus file it is marked as https, which it was previously just // for the protocol. I'll have to take a closer look this week.



--
Henry Snopek

**Comment by Chrysweel** [comment]
Hello. 

I have the same problem. 

>http://my-domain.com/Users/henrysnopek/projects/share-button/http:/fonts.gstatic.com/s/lato/v11/v0SdcGFAl2aezM9Vq_aFTQ.ttf

**Comment by hhsnopek** [comment]
So this is only present in the minified version, still looking into why this occurs

**Comment by hhsnopek** [comment]
figured out the issue and looking into alternatives and fixes

**Comment by Chrysweel** [comment]
:+1:

**Comment by hhsnopek** [comment]
The fix for this is ugly, but I'll implement it later today :)

**Comment by hhsnopek** [comment]
fixed in latest release
