### ISSUE TITLE
Can we change text of button ? 

### ISSUE THREAD

**Issue by Chrysweel** [carrot/share-button#240]
I want translate the word "Share" but I dont know change the text.

I see in code:

https://github.com/carrot/share-button/blob/master/src/share-button.js#L41

Also I see the pull request https://github.com/carrot/share-button/issues/35

But I dont find option button_text... any idea ?

**Comment by hhsnopek** [comment]
buttonText is where you can update the text of the button, that issue is prior to 1.0.x



--
Henry Snopek

**Comment by Chrysweel** [comment]
Hello @hhsnopek thanks for answering!

I have the last version and I tried use buttonText parameter, but it doesnot work... any idea ?

**Comment by hhsnopek** [comment]
I've just tested this locally with the latest build, 1.0.2, and it's working.
How are you passing the buttonText parameter?

Here's a reference to the usage of `buttonText`: https://github.com/carrot/share-button/blob/master/tests/fixtures/ui.html#L29

**Comment by acrogenesis** [comment]
```
share_button = new ShareButton({
    ui: {
      buttonText: 'Compartir'
    }
  });
```

**Comment by hhsnopek** [comment]
@acrogenesis the code you gave me works correctly for me. Whats the error that's being thrown if there is one?
![acrogenesis code example](https://cldup.com/wV-4Ebw_c4.png)

**Comment by acrogenesis** [comment]
@hhsnopek I don't see any error.

**Comment by hhsnopek** [comment]
can I get a screenshot of your button?

**Comment by hhsnopek** [comment]
@acrogenesis Ohhh. Sorry and Thank you!!! I'm going to close this out unless @Chrysweel has anymore questions?

**Comment by Chrysweel** [comment]
@hhsnopek no thanks ! :)
