### ISSUE TITLE
No button text when first time open

### ISSUE THREAD

**Issue by Bdiang** [carrot/share-button#241]
Tested at work and home on FF and Chrome. First time - no button text and icons doesn't appear on click. Also there is lag between page loading and button text showing up when press ctrl+f5. Although on localhost there is no lag.
![2015-10-15 22-46-22 2](https://cloud.githubusercontent.com/assets/1962493/10523468/019fa1c4-7394-11e5-9a21-788177178aea.png)

**Comment by hhsnopek** [comment]
Is occurring on sharebutton.co and `index.html` located in the root of the project or just within a personal/work project?

**Comment by Bdiang** [comment]
That was because slow hosting.

**Comment by hhsnopek** [comment]
:+1:
