### ISSUE TITLE
Add browserify support

### ISSUE THREAD

**Issue by MikeQuaci** [carrot/share-button#246]
The library can't be imported using browserify.

If we require the main js as ```
require('../components/share-button/src/share-button.js'); ``` and build our source with browserify we get this error:
 ```
>> SyntaxError: Unexpected token (5:7) while parsing /home/xxx/public/components/share-button/src/share-button.js while parsing file: /home/michael/Dev/workspace/nodejs/flyndo/MVP/public/components/share-button/src/share-button.js
```

**Comment by hhsnopek** [comment]
@MikeQuaci you'll need to require the `dist` build located here: `share-button/dist/share-button.js`. This is because the source is written with es2015 and requires polyfills to transpile

**Comment by MikeQuaci** [comment]
Thanks for the quick reply! So we have to build the project? I have installed share-button using bower

**Comment by hhsnopek** [comment]
At the moment yes, see #212 - I've been meaning to get around to a couple issues, this would be one of them. Give me a moment

**Comment by MikeQuaci** [comment]
Ok, I managed to make it work building the project and using those sources. I think you should add the build folder to the repository.
You should also add the build script to your package.json scripts section, so everyone can build it easily using ```npm run build ```

```
"scripts": {
    "test": "pioneer",
    "build": "gulp build"
  }

**Comment by hhsnopek** [comment]
I personally don't like having the compiled files clogging up the git history as well there's been issues in the past when someone will forget to compile and push the latest changes up with their PR. Removing them from the repo allows us to resolve both issues. Regarding the npm scripts, I'd have to add `gulp unbuild` as well, do you have any reasoning for add them to the npm script? Is it more of a connivence?

I'm currently merging a couple patches and will be deploy a release which will contain distribution for bower. :smile:

**Comment by hhsnopek** [comment]
pending the ability to publish to bower thru authorship, bower will be updated hopefully by EOD.

**Comment by MikeQuaci** [comment]
Having the build scripts in the scripts section allows npm to automatically set up $PATH to look in node_modules/.bin. So all the dependencies (also the dev one) will be in the $PATH.  In short: Users do not have to look into the code to find how to build the project, then install gulp globally and run gulp build. For more infos see this [blog post](http://substack.net/task_automation_with_npm_run) for more infos.

About build sources, if you don't want to add build folder to your main repo, the bower component should point to a shim version of the project, as jquery component points [here](https://github.com/components/jquery), but I think you have already addressed this problem.  

Thx for the support and congrats for the project!

**Comment by hhsnopek** [comment]
@MikeQuaci if you want to create a PR for the npm scripts that'd be great :)
That's exactly what I did for share-button (jquery shim), I'm just need author access to share-button as the original author isn't available :smile:

**Comment by MikeQuaci** [comment]
@hhsnopek  PR created https://github.com/carrot/share-button/pull/248

**Comment by hhsnopek** [comment]
:+1: I'll merge it in at lunch


--
Henry Snopek
