### ISSUE TITLE
only facebook doesn't work with custom title,description

### ISSUE THREAD

**Issue by arisAlexis** [carrot/share-button#249]
new ShareButton({
            url:'http://lala',
            title:'custom',
            description:'custom descr',
              networks: {
                facebook: {
                  app_id: appConfig.facebookId,
                  load_sdk:true
                }
            },
        });

I don't understand why the correct title and description works for all networks except for facebook. Any help?

**Comment by hhsnopek** [comment]
With the Facebook SDK make sure your permissions are properly set on your facebook app dashboard. Similar issues have come up in the past with the sdk and share-button, also it might be worth adding the title/description as `meta` tags to that page so `share-button` grabs from their and all web crawlers can access the same information you're passing into the config object.

**Comment by arisAlexis** [comment]
Which persmissions exactly do I need to change on the facebook dashboard?

I am implementing a list of products each one of them with it's unique title and description that's why I am not using the open graph meta tags but hoped to do it with this software. Works ok for all networks though except fb so I won't give up yet!
Is there a problem because of the many instances with different titles,descriptions you think? a bug?

**Comment by arisAlexis** [comment]
any ideas? I can't do it with meta tags on the page.

**Comment by arisAlexis** [comment]
I am closing this after doing research. It is not possible to make facebook work programmatically but it needs to be written in the docs.

**Comment by kylemac** [comment]
@arisAlexis would you be willing to add a PR with the doc update?

**Comment by arisAlexis** [comment]
@kylemac with pleasure but I am not sure if I fail to use it properly still. noone else responded.

**Comment by kylemac** [comment]
I'm thinking if we have your solution in the form of a PR - it'll help us investigate. i apologize for the delay, however, we just have not had enough time to dedicate to addressing each issue lately.

**Comment by arisAlexis** [comment]
Of course not, this is provided for free and we appreciate it :) but I really ended up putting a normal facebook button and using this software for the rest of the social networks.

The thing is that sharer.php doesn't accept custom parameters and goes to the URL and actually parses it. If this is generated from an SPA then the metatags will not be there. What I did is to prerender my page only for the facebook user-agent and serve that. But that means that the description and title fields in the configuration options are not valid for facebook.

**Comment by arisAlexis** [comment]
Final comment for this. The custom description and url is working only if the link points to a page that has the open graph headers (ie you need to prerender it if you have an SPA). If you want this in the docs I will make a PR.

**Comment by tagrudev** [comment]
I am facing the same issue can you add a description on the needed og headers ?

**Comment by arisAlexis** [comment]
@tagrudev yes sure. What I did is I serve a blank page with only the meta headers if the user agent hitting the url is facebook's and if not the normal page. 

The blank page only contains this (with handlbars markup): 

<html>
    <head>
        {{#with data}}
          <meta name="author" content="{{metaAuthor}}"/>
          <meta property="og:url"           content="{{metaUrl}}" />
          <meta property="og:type"          content="website" />
          <meta property="og:title"         content="{{metaTitle}} wrote" />
          <meta property="og:site_name" content="WriteDown"/>
          <meta property="fb:app_id" content="439874298"/>
          <meta property="og:description"   content="{{metaDescription}}" />
          <meta property="og:image"         content="{{host}}/images/logo.png" />
         {{/with}}
    </head>
    <body>
        
    </body>
</html>

this is the only way to get facebook to share the correct data because unlike the rest of the networks when you press the button it crawls the page.
