### ISSUE TITLE
close method doesn't work

### ISSUE THREAD

**Issue by changalberto** [carrot/share-button#253]

**Comment by hhsnopek** [comment]
Hey @changalberto would you be to provide me with your browser(w/version) & os so I may reproduce the error?

**Comment by changalberto** [comment]
https://github.com/carrot/share-button/blob/master/src/share-button.js#L248 <https://github.com/carrot/share-button/blob/master/src/share-button.js#L248>

Quick look, seems like someone fixed it already.

**Comment by hhsnopek** [comment]
All good to close the issue out @changalberto?

**Comment by changalberto** [comment]
Sure. Thanks

**Comment by hhsnopek** [comment]
awesome! - let me know if you run into anymore issues :smile:
