### ISSUE TITLE
Mail component not bringing up mail client

### ISSUE THREAD

**Issue by GuillermoCasanova** [carrot/share-button#255]
Hi, 

I recently integrated the share button in our site at drinktelula.com to share recipes posted on the site. The Facebook, Twitter, and G+ shares work quite well, however, the mail share does not. When clicked, nothing happens. 

Another issue I'm having is that the Facebook component isn't getting any of my customization regarding the caption, title and image. 

You can see the share button in action at: 
http://drinktelula.com/post.html#2

My JS for the button is: 

   initShareButton = function(options) {

        var description = options.description,
            title = "Delicious " + options.title + " on drinktelula.com", 
            image = options.image; 

        config = {

            title : "nothing",
            description : title,

            networks: {
                facebook : {
                    title: title,
                    caption: "OMG",
                    image: image

                },
                linkedin : {

                    enabled: false
                },
                reddit : {
                    enabled: false
                },
                pinterest : {
                    enabled: false
                },
                email: {
                    title: "Check out this delicious recipe from Telula!",
                    description: "LOVE THIS"
                }
            }
            
        };

        new ShareButton(config);

    }

            var shareButtonOptions = {
//Recipe Data is a JSON object I'm passing in. 

                description: recipeData.title,
                title : recipeData.title,
                image : "http://drinktelula.com/uploads/" + recipeData.image
            }

            initShareButton(shareButtonOptions); 

Any help on this is much appreciated! 

Thanks, 
Guillermo from Humanaut

**Comment by GuillermoCasanova** [comment]
So after some digging into the source code, I managed to get the mail button to open up the mail client after removing this line "&& i.setAttribute("onclick", "return false")" in share-button.min.js. 

Is this line necessary/what does it do?

**Comment by GuillermoCasanova** [comment]
After some digging into the source code, I found this line (937) in share-button.js was causing the issue as it was returning both 'email' and 'enabled' classes:  

if (network.className !== 'email') a.setAttribute('onclick', 'return false');

I replaced it with the line below so it targets only the first class of each 'network' element to compare it to 'email' and thus successfully not giving the element the 'return false' attr.

if (network.classList[0] !== 'email') a.setAttribute('onclick', 'return false');

Should this be implemented into master or is there something I'm doing wrong? 

Thanks. 
Guillermo

**Comment by duellsy** [comment]
:+1:

**Comment by Karlheinzniebuhr** [comment]
not yet updated in master

**Comment by hhsnopek** [comment]
see #260
