### ISSUE TITLE
Mignified files inside the main .tar.gz | comments format

### ISSUE THREAD

**Issue by vincent-guesnard** [carrot/share-button#259]
Hello,

Thank you for this amazing lib. Nice job.

1. Would you like to put your mignified version (css/js) inside the main archive for you next version please (inside a dist directory would be awesome) ?

2. For those who auto concatenate/compress librairies into a single JS (to reduce concurrents connection on our servers), you should prefer /* */ comment tags, instead of //. Else, the compiled JS will be corrupted.

Thanks,
Best regards,

Vincent

**Comment by hhsnopek** [comment]
Hey @vincent-guesnard which auto-concatenation/compress library are you using? When building and distributing the latest, we provide the minified versions that use minify (css) and uglify (js), both of which remove all comments from the code.

Regarding the dist/minified versions in the main archive I can go ahead and add the `dist` folder to the next tar/zip files (not the source files) - we've removed the `dist` folder from the repo to declutter the repo a bit :smile:
