### ISSUE TITLE
"mailto" does not work - potential bug (Confirmed Bug)

### ISSUE THREAD

**Issue by suleimana** [carrot/share-button#260]
I"m using the latest release "v1.0.3" and the email share does not work (nothing happens when you click). After some debugging I believe I found the issue.   

The email link has a "return false" function on click, which should not be there: 
```html
<li class="email enabled" data-network="email">
   <a onclick="return false" href="mailto:?subject=xxxxxxxxxxx;body=xxxxxxxxx">
 </a>
</li>
```
at line [248](https://github.com/carrot/share-button/blob/master/src/share-button.js#L248) in share-button.js file , You have the following if statement 
```js
if (network.className !== 'email')
          a.setAttribute('onclick', 'return false');
```

Since you always have multiple class names (share type && enabled )  the condition will never return true  and therefore  mailto link will have onclick="return false". 

If you replace the above if statement  the following, it should  fix the issue: 
```js
 if (!((' ' + network.className + ' ').indexOf(' ' +'email'+ ' ') > -1)){
       a.setAttribute('onclick', 'return false');
  }
```

**Comment by vincent-guesnard** [comment]
+1

**Comment by itwasmattgregg** [comment]
+1

**Comment by Chrysweel** [comment]
+1

**Comment by Karlheinzniebuhr** [comment]
+1 is there no fix for this?

**Comment by GuillermoCasanova** [comment]
+ 1

**Comment by GuillermoCasanova** [comment]
+1

**Comment by hhsnopek** [comment]
Sorry for the inactivity, this will be resolved soon!

**Comment by hhsnopek** [comment]
Just merged the fix! I'll release an update in the morning :sunrise:

**Comment by m00s** [comment]
Hi @hhsnopek, has this fix been released?
I still see the issue in chrome and safari mobile

**Comment by hhsnopek** [comment]
Hey @m00s this fix hasn't been released yet - I was hoping to do so... well 22 days ago, I'll get to this soon :smile:

**Comment by m00s** [comment]
@hhsnopek many thanks :pray:
