### ISSUE TITLE
Where has the dist folder disappeared??

### ISSUE THREAD

**Issue by paramsinghvc** [carrot/share-button#261]
I can't find the dist folder anywhere

**Comment by kylemac** [comment]
https://github.com/carrot/share-button-bower

**Comment by DesignerX** [comment]
I have this same question ! After digging around I found this link 
https://github.com/carrot/share-button/releases/tag/v1.0.3
But does that mean I need to download them manually ? then what's the point of github & bower? Any advice  would be great.

**Comment by hhsnopek** [comment]
Hey @paramsinghvc and @DesignerX - we've removed the dist folders to keep the repo clean. I've been lacking to upload all previous versions of share-button to the link above. - tho you can still grab them from the release section :)
