### ISSUE TITLE
Bug : Safari 5.1.17 failed to load SVG image inside CSS - 1.0.3

### ISSUE THREAD

**Issue by vincent-guesnard** [carrot/share-button#262]
Hello,

Test failed on Safari 5.1.17 for your version 1.0.3, each SVG image inside the CSS failed to load, resulting empty box.

Any idea ?

**Comment by hhsnopek** [comment]
hey @vincent-guesnard, I'm sorry to say but unfortunately Safari 5.1.17 is out of the coverage range for share-button. I'm personally unsure why it happens, but my assumption is that Safari 5.1.17 does not support the base64 encoded svgs or possibly `data:image/svg+xml` within the `background url` property
