### ISSUE TITLE
Bug : IE10/11 - images not centered - IE9 : Failed to load (configuration issue) - 1.0.3

### ISSUE THREAD

**Issue by vincent-guesnard** [carrot/share-button#263]
Hello,

I found one visual effect issue on IE10 and IE 11, social button aren't align into their respective boxes. (it seems that a left align is apply)

And a major issue on IE9, with a javascript crash when loading this configuration : 

var shareButton = new ShareButton({
                    ui: {
                        flyout: 'center bottom',
                        buttonText: 'PARTAGER'
                    },
                    networks: {
                        googlePlus: {enabled: true},
                        twitter: {enabled: true},
                        facebook: {enabled: true},
                        pinterest: {enabled: true},
                        reddit: {enabled: false},
                        linkedin: {enabled: false},
                        whatsapp: {enabled: false},
                        email: {enabled: true}
                    }
                });

It forces me to turn off this great plugin on these browsers (with a dirty if (!$.browser.msie || !($.browser.msie && $.browser.version == '9.0'))).

Any idea ?

PS : here is a dirty trick to fix center problem on IE10/11 : 

if($.browser.msie){
                    $('share-button .sb-social ul li').css('padding', '12px 16px');
                    $('share-button .sb-social ul li').css('width', '23px');
                }

Best regards,

Vincent

**Comment by hhsnopek** [comment]
Hey @vincent-guesnard, did you add this to #250?
