### ISSUE TITLE
Share-button breaks my current js (I think because of String.prototype.toRFC3986)

### ISSUE THREAD

**Issue by wil93** [carrot/share-button#265]
If I add share-button to my current app, I see a weird behavior and weird exceptions in the console.

Digging a bit, I found that I have a for loop like this:

    for (let i in s) {
        // do stuff
    }

And this loop iterates through all characters of the string `s`, however, there is apparently a moment when `i = "toRFC3986"`. This, obviously, makes my app launch exceptions.

I can't find any documentation on a standard `toRFC3986` method for strings... Is this library adding a `toRFC3986` method to the String class? If it is, why is it doing that?

**Comment by wil93** [comment]
I confirm that the issue is to blame on share-button itself. To reproduce, go to http://sharebutton.co/ and type this in the javascript console:

    for (var i in "asd") { console.log(i); }

This is the expected output:

    0
    1
    2

This is the output I get:

    0
    1
    2
    toRFC3986
    capFLetter

**Comment by wil93** [comment]
I just discovered that the `for..in` syntax for array-like objects [is discouraged](http://stackoverflow.com/a/1885365/747654) for this reason, so I'll change my code. However, it would be nice if the library didn't add methods to standard classes (in order to have the least footprint possible :wink:)

**Comment by hhsnopek** [comment]
Hey @wil93 you're correct when you say toRFC3986 is not a standard method in the String class, though it's easier to add to the String class, as it's the better class to be added to. Sorry for the inconvenience it brought you!

**Comment by wil93** [comment]
The alternative, of course, is to change the `toRFC3986` method to a function (or, making it a method of a different class, say `StringUtils`).

My app is small so I can change every `for..in`, but I believe this would really put off a big app from using carrot share button.

The `for..in` loop it's listed here as one of the reasons for being wary of extending native types: https://javascriptweblog.wordpress.com/2011/12/05/extending-javascript-natives/

I'm not saying that native types should not be extended, I'm saying that a library like this should be as low-footprint as possible and try as hard as possible to not break existing apps (especially when it's really easy to avoid breaking them, as it's the case in the carrot share button library).

Just saying :smile:

**Comment by hhsnopek** [comment]
you have a good point :smile: - we'll take it into consideration, if you'd like to make a PR with a proper change (as you purposed) - we'll gladly look it over!
