### ISSUE TITLE
Sharing open the iframe but navigates to share page too

### ISSUE THREAD

**Issue by paramsinghvc** [carrot/share-button#266]
When I share on any website, the iframe opens but during this my website behind it also takes the user to share page of the concerned website. Please help

![screen shot 2015-12-11 at 5 49 27 pm](https://cloud.githubusercontent.com/assets/4329912/11743696/9132fef4-a02f-11e5-9554-59152ce1cab0.png)

**Comment by paramsinghvc** [comment]
Ok turns out I had changed the share.min.js to allow navigation as the Email sharing thing wasn't working. So, ok fixed but this leads me to another issue then, is there a fix for Email sharing then?

**Comment by hhsnopek** [comment]
Hey @paramsinghvc currently we have an open issue regarding email sharing here: #260 
I'll be updating addressing the issue soon
