### ISSUE TITLE
Example animation.html doesn't work

### ISSUE THREAD

**Issue by TiagoDeSousa** [carrot/share-button#268]
animation.html in example folder doesn't work.

**Comment by elonz** [comment]
you need to run ```npm install``` from the command line in the directory of the extracted folder you downloaded. After that runs successfully, run ```gulp``` which will create the ```dist``` folder you need for the animation.html references to work.

**Comment by simsketch** [comment]
if you receive any errors while running these two commands, you will need to troubleshoot/debug your local environment. Make sure you have the most recent versions of ```npm``` and ```gulp``` installed.

**Comment by hhsnopek** [comment]
Thank you everyone for the help!
Here's another solution, you can download the bundled release and add the correct path to `examples/animation.html` :smile:
