### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by amalalili** [carrot/share-button#269]
Hi,

I have some problems:

1) I can't delete share icon: export.svg

2) I can't delete some of social accounts: Ex: LinkedIn, Pinterest.

3) Email button doesn't work.

Please help me.

**Comment by Chrysweel** [comment]
Hello @amalalili in point 3, there are an issue open 

>https://github.com/carrot/share-button/issues/260

27 days ago :(

**Comment by hhsnopek** [comment]
Hey @amalalili here's the answers to your questions :smile: 

1.) remove the icon with custom css
> remove this line - https://github.com/carrot/share-button/blob/master/src/share-button.styl#L74
2.) You're able to disable the social accounts by changing enabled to false in your config object.
> Each network has an "enable" key which you can set to false, to disable the network - https://github.com/carrot/share-button/blob/master/src/share-button.js#L53
3.) @Chrysweel is right, there's an open issue and it's well beyond it's due date to be taken care of. I apologize for that. The issue has been addressed and a fix will be released soon!

**Comment by Chrysweel** [comment]
Ok @hhsnopek dont worry ! thanks ! :)
