### ISSUE TITLE
rtl is not working correctly 

### ISSUE THREAD

**Issue by d-knafo** [carrot/share-button#274]

**Comment by hhsnopek** [comment]
Hey @d-knafo - Unfortunately as of now share-button does not support a change in `direction`, I'd recommend setting the share-button element to use `direction: ltr !important` for now. If you're looking to reorder the icons you can use config.ui.networkOrder and pass a String Array with the order you'd like (from `rtl` ) 
> https://github.com/carrot/share-button/blob/master/src/share-button.js#L43
