### ISSUE TITLE
Whatsapp not showing up

### ISSUE THREAD

**Issue by simsketch** [carrot/share-button#277]
I know it is enabled by default, but it seems no matter what I do I cannot get whatsapp icon to show up. I also noticed it says that whatsapp is enabled by default, yet on the demo page at http://sharebutton.co there is no whatsapp option.

**Comment by jessenieminen** [comment]
@simsketch Did you check the demo page on mobile?
AFAIK it doesn't (and shouldn't) show up on desktop, only on mobile devices and on my iPhone the demo page seems to work...

**Comment by simsketch** [comment]
right you are! thanks!
