### ISSUE TITLE
Facebook app_id is actually appId.

### ISSUE THREAD

**Issue by joelmats** [carrot/share-button#284]
In the docs, it says to use app_id to specify this but in the code, it's actually looking for appId.
https://github.com/carrot/share-button/blob/master/src/share-button.js#L641

**Comment by hhsnopek** [comment]
oh wow, I'm sorry about that! Thank you for bringing that up! - would you be able to update the docs and create a PR?

**Comment by joelmats** [comment]
Will do. Cheers!

**Comment by hhsnopek** [comment]
fixed in #288

**Comment by hhsnopek** [comment]
:smile:
