### ISSUE TITLE
When loading fb share with the sdk loaded, I am getting both pop up. 

### ISSUE THREAD

**Issue by joelmats** [carrot/share-button#285]
Commenting out these lines worked in eliminating the "sharer.php" from popping up:
https://github.com/carrot/share-button/blob/master/src/share-button.js#L496-L498

**Comment by hhsnopek** [comment]
Hey @joelmats - is this the same issue as #266?

**Comment by joelmats** [comment]
@hhsnopek This is slightly different. Basically, the FB SDK version opens and then right after the sharer.php version in a new window also opens because i think the href is being set when it's not suppose to.
