### ISSUE TITLE
Mail button is not working

### ISSUE THREAD

**Issue by AbrahamCovelo** [carrot/share-button#290]
I just enabled email button but it is not working at all. Tested on chrome and firefox (MAC)

**Comment by kylemac** [comment]
please refer to the `contributing.md` guideline - https://github.com/carrot/share-button/blob/master/CONTRIBUTING.md#filing-issues

**Comment by hhsnopek** [comment]
Hey @AbrahamCovelo yesterday I merged a fix in for the email button #208 - A new release will be out soon
