### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by connorjburton** [carrot/share-button#295]
## Details

NPM Install fails, see the following gist 

https://gist.github.com/connorjburton/88ceb51f12f418c875bd
#### OS(s)

OSX
### Steps to Reproduce
1. ​`sudo npm i --save-dev share-button`

**Comment by hhsnopek** [comment]
hey @connorjburton it seems that your dev environment isn't fully setup, I've found [this](http://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error) to help guide you :smile: 

closing as the error is unrelated to share-button, but let me know if you need more help!

**Comment by connorjburton** [comment]
Thanks @hhsnopek, I did try googling it beforehand, promise!

**Comment by hhsnopek** [comment]
haha I believe you! I've had a lot of issues in the past with setting up dev environments, asking is a great way to find what you need :smile:

**Comment by connorjburton** [comment]
Hi @hhsnopek, I know this issue isn't related to share-button so feel free to just ignore me :) Installed xcode and upgraded my node and i'm now getting https://gist.github.com/connorjburton/da03832e1cb55d76c715

Looks like it's an issue with cucumber or one if its dependencies? I'm really not sure.

As I said, not expecting you to solve this for me, just wondering if you ran into this before

**Comment by hhsnopek** [comment]
@connorjburton this might be the issue, you've given root permissions to npm, what you'll want to do is follow this: https://docs.npmjs.com/getting-started/fixing-npm-permissions

I also recommend going ahead afterwards and reinstalling npm with these commands:

```
npm cache clean -f
npm install -g n
n stable
npm install npm -g
```

after all that remove the `node_modules` folder in the project and run `npm i` to install all of your project dependencies, you might want to add `share-button` to your `package.json` prior to running `npm i`

**Comment by connorjburton** [comment]
Hi @hhsnopek - sorry forgot to reply to you, I did try above but it didn't work.

No worries though, I will fix it somehow.

Thanks for the help
