### ISSUE TITLE
Facebook options description not working

### ISSUE THREAD

**Issue by wraithseeker** [carrot/share-button#296]
## Details

I am editing facebook's description displayed by share-button but when I click share by facebook, I am not getting the string value that I inputted under description.

```
$(function() {
        var options = {
            ui: {
                flyout: "bottom right"
             },
            networks: {
                facebook: {
                    description: "<%= @news_description %>"

                }
            }
        }
        var shareButton = new ShareButton('.share-button',options);
    });
```

**Comment by wraithseeker** [comment]
I read through the facebook docs https://developers.facebook.com/docs/sharing/webmasters/crawler and I managed to solve this problem through another way by providing the og:description and og:title tags in my header which are dynamically added to the page.

**Comment by hhsnopek** [comment]
:+1: glad you solved the problem!
