### ISSUE TITLE
SVGs not working with latest version of Chrome

### ISSUE THREAD

**Issue by gauravmak** [carrot/share-button#306]
Not working in [main site](https://sharebutton.co/) as well. Check attached.
![share button test](https://cloud.githubusercontent.com/assets/11887260/15014402/6f132752-1223-11e6-9ce6-69abb4d76e83.png)

**Comment by rcamposp** [comment]
I'm having the same issue. See #305

**Comment by gauravmak** [comment]
Thank @rcamposp
